### ISSUE TITLE
ACF5: Import Creates Duplicates

### ISSUE THREAD

**Issue by jambox** [hoppinger/advanced-custom-fields-wpcli#26]
When I run the `import` command I end up with duplicates of every `field` and `field-group` in my DB. I noticed that the dupes have the same `uniqid`. I noticed in fcc137a40fb69499b0d95cd6722ac208ee0a4210 you moved from importing `.php` to `.json` but maybe it's still importing from both somehow? I browsed the code and didn't see any functions iterating over `.php` files, but that's as far as I got.

_**At first I thought this might have been because of an udpate from ACF v4 to v5, but I did some testing and I don't believe it has to do with that. I wouldn't completely rule it out though._

**Comment by jmslbam** [comment]
Can confirm this issue: ACF Pro 5.2.2. with current master.

**Comment by sebastiaandegeus** [comment]
Try out the `feature/version2` branch for now. This should fix most issues. We still need to switch master and the feature/version2 branch but haven't come around to it.

**Comment by jmslbam** [comment]
Slowchat, but thanks for tip :+1:

**Comment by lsmith77** [comment]
I can confirm that the ``feature/version2`` works much better with export/import .. release? :)

**Comment by sebastiaandegeus** [comment]
Yes, we should this release this. I've been preoccupied for a long period of time because of personal health reasons. I will try to get the releases and branches fixed again.

**Comment by peschee** [comment]
@sebastiaandegeus Any updates on this? For me, the latest release as well as the `feature/version2` branch produce new entries (duplicates) each time I run the `wp acf import` command.

**Comment by sebastiaandegeus** [comment]
@peschee Yes, I have a team working on this for the past couple of weeks sorting working on a new release. This release would add automatic tests. We have a test for this bug and I can confirm that it's working in the upcoming version 3 release. Timeline for the release is this or next week.

**Comment by peschee** [comment]
Great to hear that, thanks for getting back to me.

**Comment by peschee** [comment]
@sebastiaandegeus Any updates on this?

**Comment by adeyjones** [comment]
Have just found this thread but it's still occuring, almost 12 months on from previous comment.

**Comment by sebastiaandegeus** [comment]
The latest version of this plugin does not create duplicates. Please upgrade to the latest version (already used in production for months on our sites).
