### ISSUE TITLE
ACF5: Command 'wp acf import all' doesn't work but 'wp acf import' > '1' does

### ISSUE THREAD

**Issue by jambox** [hoppinger/advanced-custom-fields-wpcli#27]
It seems that `wp acf import all` fails silently. From the command line, there's no sign of the script failing, but there's also no output and no visible results in the db. If I run `wp acf import` and then type `1` for 'all', I see the correct behavior, but it looks like I can't execute the command fully.

**Comment by hatto** [comment]
Hi! i have the same problem during export. 'wp acf export all' offers me:
 1. active_child_theme: <html-root>/wp-content/themes/onlinetoro/field-groups/
 2. child_themes_shared: <html-root>/field-groups/shared-childs/

I've tried with parameters at the end of command, but doesnt work. so I cant use it in automatic deploy.

**Comment by sebastiaandegeus** [comment]
Please use `wp acf import --all` with the latest version of the plugin.
