### ISSUE TITLE
Missing `ACFCommand.php` in `src`

### ISSUE THREAD

**Issue by jmslbam** [hoppinger/advanced-custom-fields-wpcli#36]
My ACF upgrade to ACF Pro  hasn't ran yet for and old ACF field, but the files al ready. So the version is still the old version. I found out that a whole file is missing and returns an fatal error here https://github.com/hoppinger/advanced-custom-fields-wpcli/blob/feature/version2/src/Plugin.php#L15

```
include 'ACFCommand.php';
WP_CLI::add_command( 'acf', 'ACFCommand' );
```

There is only 1 file within the directory, just so you know... https://github.com/hoppinger/advanced-custom-fields-wpcli/tree/feature/version2/src/Commands

**Comment by sebastiaandegeus** [comment]
This issue is very old, It's probably fixed in the latest release. I'm closing this issue.
