### ISSUE TITLE
requesting 'sync' command

### ISSUE THREAD

**Issue by joelstransky** [hoppinger/advanced-custom-fields-wpcli#49]
Are there any plans to implement the ability to sync fields that have new acf-json data?

**Comment by jgraup** [comment]
It shouldn't be too difficult to add. See https://support.advancedcustomfields.com/forums/topic/automatic-synchronized-json/

**Comment by sebastiaandegeus** [comment]
Hi, currently there are no plans to add this feature. It goes against the way this tool is supposed to be used.

The general way of using this tool is to only have the ACF fields in your database when you are editing your fields. In all other cases all ACF fields groups should not be in the database.

For production and even development websites no ACF fields should be in the database. They will get loaded from the exported files at runtime. 

For example; you have a website where you want to edit the exported fields:
- Run `wp acf clean` to make sure nothing ACF is in the database
- `wp acf import` to import your fieldgroup that you want to edit
- edit the fieldgroup in the ACF admin interface
- run `wp acf export` to export your fields
- add the exported fields to your VCS (Git/SVN)
- run `wp acf clean` to clean up after your work

We run dozens of WordPress sites and zero have any ACF fields groups in the database on production.

**Comment by sebastiaandegeus** [comment]
When editing fieldgroups inside the json or php files itself to make simple changes (i.e. a label text change) you don't have to import the fieldgroups at all. You can just edit in the files and add to VCS right away. Right now it's a bit tedious to edit both the json and php files but in the upcoming release only json files are exported to that makes it much easier.
