### ISSUE TITLE
any plans for a new release?

### ISSUE THREAD

**Issue by lsmith77** [hoppinger/advanced-custom-fields-wpcli#50]

**Comment by sebastiaandegeus** [comment]
Yes, the branch [release/version3](https://github.com/hoppinger/advanced-custom-fields-wpcli/tree/release/version3) contains the new version 3. We're still testing it internally and will make a release after we are sure it works well.

**Comment by lsmith77** [comment]
ping :)

**Comment by sebastiaandegeus** [comment]
Hello, sorry for the delay. I've been a bit overwhelmed with work. I will try to get some co-workers to get this moving. I'll report back when I have a timeline.

**Comment by sebastiaandegeus** [comment]
@lsmith77 I have had two developers working on this for the last two weeks to improve the readme, handle the issues on github, add automatic tests and also add a release script for wordpress.org/plugins. Things are moving again. The timeline for a release is this or next week.

**Comment by lsmith77** [comment]
much appreciated!

**Comment by sebastiaandegeus** [comment]
@lsmith77 Version 3.0.0 has been released. Please let us know if everything is working for you.

**Comment by lsmith77** [comment]
@sebastiaandegeus hmm it seems like the expected data structure for imports was totally changed?

**Comment by sebastiaandegeus** [comment]
Yes that is correct. To upgrade follow the upgrade instructions. Which are:

1. import all field groups
2. upgrade acf-wpcli plugin to version 3
3. set field groups directory with new filter
4. export all field groups to new location
5. possible clean up old export files
