### ISSUE TITLE
Fields stay visible on page or post after deleting them on the custom fields page

### ISSUE THREAD

**Issue by SjoerdVermeijden** [hoppinger/advanced-custom-fields-wpcli#65]
Hello Sebastiaan,

Whenever I delete a custom field from the custom fields page, the field stays visible on the post or page it was assigned to. If i then deactivate the wp acf cli plugin the field does disappear.

Is there something i'm not understanding?

Kind regards,

Sjoerd

**Comment by sebastiaandegeus** [comment]
Hi Sjoerd, 

If you have exported the field groups then the fields will still be hooked on the pages/posts/etc you set the conditions for in your fields. That is the goal of the plugin. So you don't need the ACF fields in the database and you can add the to GIT or SVN.

If you want to remove a exported field group completely you have to remove those exported files. 

Does this answer your question?

**Comment by SjoerdVermeijden** [comment]
Hi Sebastian,

Thank you for your reply. I understand now why the fields are still visible. 
Where exactly do i remove those exported files? I've found a field-groups folder inside my theme, but when i delete the field group from that folder the fields are still visible on the page.

Thank you!

Sjoerd
