### ISSUE TITLE
plugin dead?

### ISSUE THREAD

**Issue by wstoettinger** [hoppinger/advanced-custom-fields-wpcli#91]
is this plugin still being developed? the last commits seem to be from two years ago and there are a lot of branches/pull requests. 
would be sad to see this plugin die.

**Comment by sebastiaandegeus** [comment]
It's not dead, we use it all the time in production. Development has not been very active. Some of the pull request have been fixed in the most recent version. 

I'll allocate some of our company resources to working through the open pull requests and issues.

**Comment by sebastiaandegeus** [comment]
https://github.com/hoppinger/advanced-custom-fields-wpcli/projects/1

**Comment by wstoettinger** [comment]
very nice to hear :)
